CREATE LOGIN D_directeur
WITH PASSWORD = 'directeur1234*',
DEFAULT_DATABASE=NaturaDerm,
DEFAULT_LANGUAGE=French

CREATE LOGIN M_manager1
WITH PASSWORD = 'manager1234*',
DEFAULT_DATABASE=NaturaDerm,
DEFAULT_LANGUAGE=French

CREATE LOGIN C_test1
WITH PASSWORD = 'test1234*',
DEFAULT_DATABASE=NaturaDerm,
DEFAULT_LANGUAGE=French

USE NaturaDerm;
CREATE USER D_directeur FOR LOGIN D_directeur;
GO
CREATE USER M_manager1 FOR LOGIN M_manager1;
GO
CREATE USER C_test1 FOR LOGIN C_test1;
GO

CREATE ROLE R_CONSEILLER1;
GRANT SELECT ON SCHEMA::Vente TO R_CONSEILLER1;
GO
ALTER ROLE R_CONSEILLER1 ADD MEMBER C_test1;
GRANT SELECT on manager.fournisseur TO C_test1;


CREATE ROLE R_MANAGER1;
GRANT SELECT, INSERT, UPDATE ON SCHEMA::Manager TO R_MANAGER1;
GO
GRANT SELECT, INSERT ON SCHEMA::Vente TO R_MANAGER1;
GO
ALTER ROLE R_MANAGER1 ADD MEMBER M_manager1;
GRANT UPDATE on vente.composant TO M_manager1 WITH GRANT OPTION;

CREATE ROLE R_DIRECTEUR1;
GRANT SELECT, INSERT, UPDATE, EXECUTE ON SCHEMA::Manager TO R_DIRECTEUR1;
GO
GRANT SELECT, INSERT, UPDATE, EXECUTE ON SCHEMA::Vente TO R_DIRECTEUR1;
GO
ALTER ROLE R_DIRECTEUR1 ADD MEMBER D_directeur;