CREATE LOGIN D_directeur1
WITH PASSWORD = 'directeur1234*',
DEFAULT_DATABASE=NaturaDerm,
DEFAULT_LANGUAGE=French

CREATE LOGIN M_manager11
WITH PASSWORD = 'manager1234*',
DEFAULT_DATABASE=NaturaDerm,
DEFAULT_LANGUAGE=French

CREATE LOGIN C_test11
WITH PASSWORD = 'test1234*',
DEFAULT_DATABASE=NaturaDerm,
DEFAULT_LANGUAGE=French

USE NaturaDerm;
CREATE USER D_directeur1 FOR LOGIN D_directeur1;
GO
CREATE USER M_manager11 FOR LOGIN M_manager11;
GO
CREATE USER C_test11 FOR LOGIN C_test11;
GO

CREATE ROLE R_CONSEILLER11;
GRANT SELECT ON SCHEMA::Vente TO R_CONSEILLER11;
GO
ALTER ROLE R_CONSEILLER11 ADD MEMBER C_test11;
GRANT SELECT on manager.fournisseur TO C_test11;


CREATE ROLE R_MANAGER11;
GRANT SELECT, INSERT, UPDATE ON SCHEMA::Manager TO R_MANAGER11;
GO
GRANT SELECT, INSERT ON SCHEMA::Vente TO R_MANAGER11;
GO
ALTER ROLE R_MANAGER1 ADD MEMBER M_manager11;
GRANT UPDATE on vente.composant TO M_manager11 WITH GRANT OPTION;

CREATE ROLE R_DIRECTEUR11;
GRANT SELECT, INSERT, UPDATE, EXECUTE ON SCHEMA::Manager TO R_DIRECTEUR11;
GO
GRANT SELECT, INSERT, UPDATE, EXECUTE ON SCHEMA::Vente TO R_DIRECTEUR11;
GO
ALTER ROLE R_DIRECTEUR11 ADD MEMBER D_directeur1;